import 'package:coffee_cookies/core/constants/app_asset.dart';

class CategoryDataModel {
  final String id;
  final String nameCategory;
  final String title;
  final String image;
  final String price;
  final bool isFavourite;

  CategoryDataModel({
    required this.id,
    required this.nameCategory,
    required this.title,
    required this.image,
    required this.price,
    required this.isFavourite,
  });

  static List<String> categoryTabs = [
    'All',
    'Coffee',
    'Cookies',
    'Bakery',
    'Espresso',
    'Mocha',
    'Latte',
  ];

  static List<CategoryDataModel> categoryDataList = [
    CategoryDataModel(
      id: '1',
      nameCategory: 'Coffee',
      title: 'Americano Coffee',
      image: AppAsset.americanoCoffee,
      price: "100",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '2',
      nameCategory: 'Coffee',
      title: 'Coffee Flavor',
      image: AppAsset.coffeeFlavorCoffee,
      price: "200",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '3',
      nameCategory: 'Coffee',
      title: 'Cold Brew Coffee',
      image: AppAsset.coldBrewCoffee,
      price: "300",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '4',
      nameCategory: 'Coffee',
      title: 'French Press Coffee',
      image: AppAsset.frenchPressCoffee,
      price: "400",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '5',
      nameCategory: 'Coffee',
      title: 'Turkish Coffee',
      image: AppAsset.turkishCoffee,
      price: "500",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '6',
      nameCategory: 'Cookies',
      title: 'Banana Chocolate Chip Cookies',
      image: AppAsset.bananaChocolateChipCookies,
      price: "100",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '7',
      nameCategory: 'Cookies',
      title: 'Caramel Crunch Cookies',
      image: AppAsset.caramelCrunchCookies,
      price: "130",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '8',
      nameCategory: 'Cookies',
      title: 'Chocolate Chip Cookies',
      image: AppAsset.chocolateChipCookies,
      price: "60",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '9',
      nameCategory: 'Cookies',
      title: 'Chocolate Cookies',
      image: AppAsset.chocolateCookies,
      price: "80",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '10',
      nameCategory: 'Cookies',
      title: 'Cocoa And Melon Cookies',
      image: AppAsset.cocoaAndMelonCookies,
      price: "40",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '11',
      nameCategory: 'Cookies',
      title: 'Milky Way Sweet Cookies',
      image: AppAsset.milkyWaySweetCookies,
      price: "70",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '12',
      nameCategory: 'Bakery',
      title: 'Donuts Bakery',
      image: AppAsset.donutsBakery,
      price: "120",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '13',
      nameCategory: 'Bakery',
      title: 'Flaky Bakery',
      image: AppAsset.flakyBakery,
      price: "140",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '14',
      nameCategory: 'Bakery',
      title: 'Cinnamon Bakery',
      image: AppAsset.cinnamonBakery,
      price: "135",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '15',
      nameCategory: 'Bakery',
      title: 'Cupcake Bakery',
      image: AppAsset.cupcakeBakery,
      price: "85",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '16',
      nameCategory: 'Espresso',
      title: 'Espresso With Steamed',
      image: AppAsset.espressoWithSteamedEspresso,
      price: "100",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '17',
      nameCategory: 'Espresso',
      title: 'Lungo Espresso',
      image: AppAsset.lungoEspresso,
      price: "220",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '18',
      nameCategory: 'Espresso',
      title: 'Macchiato Espresso',
      image: AppAsset.macchiatoEspresso,
      price: "135",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '19',
      nameCategory: 'Espresso',
      title: 'Single Espresso',
      image: AppAsset.singleEspresso,
      price: "105",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '20',
      nameCategory: 'Mocha',
      title: 'Classic Mocha',
      image: AppAsset.classicMocha,
      price: "110",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '21',
      nameCategory: 'Mocha',
      title: 'Iced Mocha',
      image: AppAsset.icedMocha,
      price: "125",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '22',
      nameCategory: 'Mocha',
      title: 'Peppermint Mocha',
      image: AppAsset.peppermintMocha,
      price: " 140",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '23',
      nameCategory: 'Latte',
      title: 'Caramel Latte',
      image: AppAsset.caramelLatte,
      price: "135",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '24',
      nameCategory: 'Latte',
      title: 'Hazelnut Latte',
      image: AppAsset.hazelnutLatte,
      price: "175",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '25',
      nameCategory: 'Latte',
      title: 'Iced Latte',
      image: AppAsset.icedLatte,
      price: "155",
      isFavourite: false,
    ),
    CategoryDataModel(
      id: '26',
      nameCategory: 'Latte',
      title: 'Vanilla Latte',
      image: AppAsset.vanillaLatte,
      price: "140",
      isFavourite: false,
    ),
  ];
}
